version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix-server/data:/var/lib/postgresql/data
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - 80:8080
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    container_name: zabbix-agent
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - zabbix-network

networks:
  zabbix-network:
